#!/usr/bin/env bash

# Update package list and install Nginx
sudo apt-get update -y -qq
sudo apt-get install nginx -y

# Allow Nginx through the firewall
sudo ufw allow 'Nginx HTTP'

# Create a custom index file with "Hello World!"
echo "Hello World" | sudo tee /var/www/html/index.html

# Configure Nginx to perform a 301 redirect for /redirect_me
echo '
server {
    listen 80 default_server;
    server_name _;

    location /redirect_me {
        return 301 https://www.youtube.com;
    }

    # ... other Nginx configuration ...

}' | sudo tee /etc/nginx/sites-available/redirect_me

# Create a symbolic link to enable the redirect configuration
sudo ln -s /etc/nginx/sites-available/redirect_me /etc/nginx/sites-enabled/

# Restart Nginx
sudo service nginx restart

# Exit with success
exit 0

