#!/usr/bin/env bash
# Install Nginx and configure custom 404 page

# Update package lists
sudo apt-get update

# Install Nginx
sudo apt-get -y install nginx

# Allow Nginx HTTP traffic
sudo ufw allow 'Nginx HTTP'

# Create a custom 404 page with the expected message
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

# Configure Nginx to use the custom 404 page
sudo sed -i '/listen 80 default_server/a error_page 404 /404.html;' /etc/nginx/sites-available/default

# Reload Nginx to apply the changes
sudo service nginx reload

# Start Nginx
sudo service nginx start

