#!/usr/bin/env bash
# Double the number of webservers.

# Update the package list
sudo apt-get update

# Install Nginx
sudo apt-get -y install nginx

# Create and configure the main HTML file
sudo echo 'Holberton School' | sudo tee /var/www/html/index.html

# Create a directory for error pages
sudo mkdir -p /var/www/error

# Create a custom 404 error page
sudo echo "Ceci n'est pas une page" | sudo tee /var/www/error/404.html

# Modify the Nginx configuration file to add custom headers
sudo sed -i '/server_name _/a add_header X-Served-By $hostname;' /etc/nginx/sites-available/default

# Restart Nginx to apply the changes
sudo service nginx restart

echo "Nginx configured successfully."

