#!/usr/bin/env bash
# This script provides the answers to the types of network questions

# Question 1: What type of network a computer in local is connected to?
echo "LAN"
# Answer: 3

# Question 2: What type of network could connect an office in one building to another office in a building a few streets away?
echo "WAN"
# Answer: 2

# Question 3: What network do you use when you browse www.google.com from your smartphone (not connected to the Wifi)?
echo "Internet"
# Answer: 1

