#!/usr/bin/env bash
# This script provides the answers to the MAC and IP address questions

# Question 1: What is a MAC address?
echo "The unique identifier of a network interface"
# Answer: 2

# Question 2: What is an IP address?
echo "Is to devices connected to a network what postal address is to houses"
# Answer: 1

