#!/usr/bin/env bash
# This script provides the answers to the UDP and TCP questions

# Question 1: Which statement is correct for the TCP box?
echo "It is a protocol that is transferring data in a slow way but surely"
# Answer: 1

# Question 2: Which statement is correct for the UDP box?
echo "It is a protocol that is transferring data in a fast way and might lose data along in the process"
# Answer: 2

# Question 3: Which statement is correct for the TCP worker?
echo "May I increase the rate at which I am sending you boxes?"
# Answer: 2

