#!/usr/bin/env bash
# server-01 login

# Start ssh-agent (if not already running)
eval "$(ssh-agent -s)"

# Add your private key to the ssh-agent
ssh-add ~/.ssh/school

# SSH into your server using the correct IdentityFile option
ssh -i ~/.ssh/school ubuntu@52.3.251.211

