#!/usr/bin/env bash
# This script configures the localhost and facebook.com IP addresses in /etc/hosts

# Backup the original /etc/hosts file
sudo cp /etc/hosts /etc/hosts.bak

# Update localhost IP address
echo "127.0.0.2 localhost" | sudo tee -a /etc/hosts

# Update facebook.com IP address
echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts

